### ISSUE TITLE
Feature: Add "fit to width" scaling of viewport

### ISSUE THREAD

**Issue by IllusionMH** [auchenberg/vscode-browser-preview#37]
First of all I want to thank you for this extension. I like the idea and implementation, and it helps me with prototyping fir side projects.

As I can see - size of browser preview affects viewport size that is rendered by headless chrome, which is expected but not ideal for my case.

I'm working on website where I should see full desktop version. At this moment I have to stack editors and preview vertically (unusual and uncomfortable to me, because of limited vertical space left for editors and total nightmare when terminal panel is open 😆 )

As possible solution for my case I can see:
1) Set fixed window size for headless chrome
2) Render output image scaled down, so it will fit to width.
3) Action to switch between regular and "fit to width" modes

Will you consider this feature or it is out of scope?

**Comment by auchenberg** [comment]
I think we could solve this scenario by adding a "device emulation" where one of the devices you can choose is a desktop. Much similar to the device emulation Chrome already offers. Would this work @IllusionMH ?

**Comment by IllusionMH** [comment]
Looks like it will solve first part, and will render site with 1920px width.
But will it allow second point - "fit to width"?
In my case I want to make Browser preview tab width like 1/3 or 1/4 of screen (so I will have enough space for code and file explorer/git/etc.) and downscaled version of the page will be better than need for horizontal scrolling through page.
In combination with dynamic change of emulation height during resize (to match free vertical space after downscaling) will be nice to have, and will allow to see whole page without any scroll.

**Comment by auchenberg** [comment]
@IllusionMH You can now try this out by pull https://github.com/auchenberg/vscode-browser-preview/pull/79, and running from source.

**Comment by IllusionMH** [comment]
Tried PR branch, but looks like it doesn't work on my machine 😭 

When I use Launch Extension in master branch - it all works as expected, I can see any site (except `example.com` for some reason 0_o)

When I launch same task from PR branch (after `npm i` of course) - it is always "blank" page.
![image](https://user-images.githubusercontent.com/1312662/55292410-4b7aad00-53f3-11e9-9f80-e51dff7b8d21.png)
<details>
<summary>Debug log looks clear</summary>

► browserPage.send Page.enable
► browserPage.send Page.getNavigationHistory
► browserPage.send Page.navigate
◀ browserPage.received Page.frameStartedLoading
◀ browserPage.received Page.frameNavigated
◀ browserPage.received Page.frameAttached
◀ browserPage.received Page.frameStartedLoading
◀ browserPage.received Page.frameNavigated
◀ browserPage.received Page.domContentEventFired
◀ browserPage.received Page.frameStoppedLoading
◀ browserPage.received Page.loadEventFired
◀ browserPage.received Page.frameStoppedLoading
◀ browserPage.received null
</details>

Sometimes I receive an exception, but it looks like it is only when I close last Browser Preview tab (doubt that it is related)

<details>
<summary>Trace</summary>

◀ browserPage.received null
rejected promise not handled within 1 second: Error: Protocol error (Target.detachFromTarget): Target closed.
stack trace: Error: Protocol error (Target.detachFromTarget): Target closed.
	at send.Promise (c:\web\projects\vscode-browser-preview\node_modules\puppeteer-core\lib\Connection.js:73:56)
	at new Promise (<anonymous>)
	at Connection.send (c:\web\projects\vscode-browser-preview\node_modules\puppeteer-core\lib\Connection.js:72:12)
	at CDPSession.detach (c:\web\projects\vscode-browser-preview\node_modules\puppeteer-core\lib\Connection.js:223:28)
	at CDPSession.<anonymous> (c:\web\projects\vscode-browser-preview\node_modules\puppeteer-core\lib\helper.js:145:23)
	at BrowserPage.dispose (c:\web\projects\vscode-browser-preview\build\ext-src\browserPage.js:16:21)
	at BrowserViewWindow.dispose (c:\web\projects\vscode-browser-preview\build\ext-src\extension.js:199:30)
	at launch._panel.onDidDispose (c:\web\projects\vscode-browser-preview\build\ext-src\extension.js:116:45)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at c.dispose (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:579:799)
	at l.$onDidDisposeWebviewPanel (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:582:468)
	at d._doInvokeHandler (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
rejected promise not handled within 1 second: Error: Protocol error (Target.closeTarget): Target closed.
stack trace: Error: Protocol error (Target.closeTarget): Target closed.
	at send.Promise (c:\web\projects\vscode-browser-preview\node_modules\puppeteer-core\lib\Connection.js:73:56)
	at new Promise (<anonymous>)
	at Connection.send (c:\web\projects\vscode-browser-preview\node_modules\puppeteer-core\lib\Connection.js:72:12)
	at Page.close (c:\web\projects\vscode-browser-preview\node_modules\puppeteer-core\lib\Page.js:949:38)
	at Page.<anonymous> (c:\web\projects\vscode-browser-preview\node_modules\puppeteer-core\lib\helper.js:145:23)
	at BrowserPage.dispose (c:\web\projects\vscode-browser-preview\build\ext-src\browserPage.js:17:19)
	at BrowserViewWindow.dispose (c:\web\projects\vscode-browser-preview\build\ext-src\extension.js:199:30)
	at launch._panel.onDidDispose (c:\web\projects\vscode-browser-preview\build\ext-src\extension.js:116:45)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at c.dispose (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:579:799)
	at l.$onDidDisposeWebviewPanel (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:582:468)
	at d._doInvokeHandler (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Users\Andrii\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
► browserPage.send Page.enable
► browserPage.send Page.getNavigationHistory
► browserPage.send Page.navigate
◀ browserPage.received Page.frameStartedLoading
◀ browserPage.received Page.frameNavigated
◀ browserPage.received Page.frameAttached
◀ browserPage.received Page.frameStartedLoading
◀ browserPage.received Page.domContentEventFired
◀ browserPage.received Page.frameNavigated
◀ browserPage.received Page.frameStoppedLoading
◀ browserPage.received Page.loadEventFired
◀ browserPage.received Page.frameStoppedLoading
</details>


VS Code version: Code - Insiders 1.33.0-insider (4039ea871879ef8f654f27df5c32d209104b3a44, 2019-03-29T10:53:36.965Z)
Chrome version: 73.0.3683.86 (Official Build) (64-bit)
OS version: Windows_NT x64 10.0.18865

**Comment by auchenberg** [comment]
Interesting @IllusionMH. Never seen that icon before on the canvas there..

How do you start Browser Preview? From the icon on in the sidebar?

**Comment by IllusionMH** [comment]
Yes, that's what I do.

May be that icon is on that background that is visible because page rendered as 0px x 0px (if top right corner info is true)

I've enabled verbose logging and logging and looks like there is infinite loop in my case.

CPU load goes high after launching Browser Preview tab (from icon in the sidebar) and fan became loud.
These four repeating lines appear from time to time (my guess is that DevTools have problems with logging in such kind of loop).

Sorry for big screenshot: 
![image](https://user-images.githubusercontent.com/1312662/55293960-019ac280-5405-11e9-9e4b-31fef60e3f1f.png)

**Comment by auchenberg** [comment]
@IllusionMH Funky. If you start Browser Preview, and opens a new chrome instance, goes to `chrome://inspect`, and enables network targets for `localhost:9222`, does the tab show up? What happens if you try to open Chrome DevTools for that tab?

**Comment by IllusionMH** [comment]
Looks like there are 2 tabs instead of one opened: aboit:blank and tab from preview.
And tab for preview seems normal (only exception is check if cookie policies were viewed).

![image](https://user-images.githubusercontent.com/1312662/55294916-3c562800-5410-11e9-988b-24a22a225641.png)

**Comment by auchenberg** [comment]
Alright, so the Headless Chrome instance is running as expected. That's interesting. So this is a problem with the Browser Preview front-end that runs inside VS Code.

**Comment by auchenberg** [comment]
@IllusionMH Can you try this build?  (install from VSIX ) after you have unzipped.

[vscode-browser-preview-0.5.0.vsix.zip](https://github.com/auchenberg/vscode-browser-preview/files/3027160/vscode-browser-preview-0.5.0.vsix.zip)

**Comment by IllusionMH** [comment]
@auchenberg same problems as with extension host (checked on both latest insiders and stable versions)
<details>
<summary>Console log after launching Browser Preview for the first time</summary>

```
extensionHost.ts:215 Extension Host
extensionHost.ts:216 Debugger attached.

log.ts:167  WARN UNRESPONSIVE extension host, 'auchenberg.vscode-browser-preview' took 99% of 1029.304ms, saved PROFILE here: 'C:\Users\Andrii\AppData\Local\Temp\exthost-57614c.cpuprofile' (4) [{…}, {…}, {…}, {…}]
webviewElement.ts:392 [Embedded Page] [object Object]
console.ts:134 [Extension Host] ► browserPage.send Page.enable (at BrowserPage.send (c:\Users\Andrii\.vscode-insiders\extensions\auchenberg.vscode-browser-preview-0.5.0\build\ext-src\browserPage.js:20:17))
console.ts:134 [Extension Host] ► browserPage.send Page.getNavigationHistory (at BrowserPage.send (c:\Users\Andrii\.vscode-insiders\extensions\auchenberg.vscode-browser-preview-0.5.0\build\ext-src\browserPage.js:20:17))
webviewElement.ts:392 [Embedded Page] [object Object]
webviewElement.ts:392 [Embedded Page] viewport.calculateViewport
webviewElement.ts:392 [Embedded Page] app.onViewportChanged.size
webviewElement.ts:392 [Embedded Page] [object Object]
webviewElement.ts:392 [Embedded Page] viewport.calculateViewport
webviewElement.ts:392 [Embedded Page] app.onViewportChanged.size

<...and so on many times until I closed the tab...>

webviewElement.ts:392 [Embedded Page] [object Object]
webviewElement.ts:392 [Embedded Page] viewport.calculateViewport
webviewElement.ts:392 [Embedded Page] app.onViewportChanged.size
webviewElement.ts:392 [Embedded Page] [object Object]
<closed tab here>
console.ts:134 [Extension Host] ◀ browserPage.received null (at Function.launch.client.else (c:\Users\Andrii\.vscode-insiders\extensions\auchenberg.vscode-browser-preview-0.5.0\build\ext-src\browserPage.js:76:21))
```
</details>

Not sure what causes infinite loop.

Unfortunately I don't have enough knowledge of extension code and time to debug this issue locally, but will try when have time.

**Comment by auchenberg** [comment]
@IllusionMH Aha, I think I know what  it is. Stay tuned. Thanks for testing!

**Comment by auchenberg** [comment]
@IllusionMH Can you try to pull the branch and run a `npm start` followed by opening `http://localhost:3000` in Chrome? Do you still have that infinite loop? Can't reproduce here, so so wondering what's going in

**Comment by IllusionMH** [comment]
@auchenberg sorry for delay, only now had a chance to take look at this.
Unfortunately - looks like I still have problem even inside Chrome.
1) `npm i`
2) `npm start`
3) Opened `https://localhost:3000`

Console has a lot of logs that looks same:
![image](https://user-images.githubusercontent.com/1312662/55689932-a84a0a80-5993-11e9-8cc4-dcac64cf51e0.png)

Pause on uncaught exceptions revealed:

`Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`
<details>
<summary>error.stack</summary>

```
Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:57:19)
    at scheduleWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19717:9)
    at Object.enqueueSetState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12936:9)
    at App.Component.setState (webpack-internal:///./node_modules/react/cjs/react.development.js:356:20)
    at App._callee2$ (webpack-internal:///./src/App.tsx:437:22)
    at tryCatch (webpack-internal:///./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:5:24)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:9)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:34:7)
    at new Promise (<anonymous>)
    at App.eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:23:12)
    at App.onViewportChanged (webpack-internal:///./src/App.tsx:453:35)
    at Viewport.emitViewportChanges (webpack-internal:///./src/components/viewport/viewport.tsx:277:18)
    at Viewport.calculateViewportSize (webpack-internal:///./src/components/viewport/viewport.tsx:231:14)
    at Viewport.calculateViewport (webpack-internal:///./src/components/viewport/viewport.tsx:171:12)
    at App.eval (webpack-internal:///./src/App.tsx:440:35)
    at callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11743:16)
    at commitUpdateEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11783:11)
    at commitUpdateQueue (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11771:7)
    at commitLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17030:15)
    at commitAllLifeCycles (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18512:11)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:147:18)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:196:20)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:250:35)
    at commitRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18717:11)
    at completeRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20247:7)
    at performWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20170:13)
    at performWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20075:11)
    at performSyncWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20049:7)
    at requestWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19904:9)
    at scheduleWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19711:9)
    at Object.enqueueSetState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12936:9)
    at App.Component.setState (webpack-internal:///./node_modules/react/cjs/react.development.js:356:20)
    at App._callee2$ (webpack-internal:///./src/App.tsx:437:22)
    at tryCatch (webpack-internal:///./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (webpack-internal:///./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (webpack-internal:///./node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:5:24)
    at _next (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:27:9)
    at eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:34:7)
    at new Promise (<anonymous>)
    at App.eval (webpack-internal:///./node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:23:12)
    at App.onViewportChanged (webpack-internal:///./src/App.tsx:453:35)
    at Viewport.emitViewportChanges (webpack-internal:///./src/components/viewport/viewport.tsx:277:18)
    at Viewport.calculateViewportSize (webpack-internal:///./src/components/viewport/viewport.tsx:231:14)
    at Viewport.calculateViewport (webpack-internal:///./src/components/viewport/viewport.tsx:171:12)
    at Viewport.handleViewportResize (webpack-internal:///./src/components/viewport/viewport.tsx:241:12)
    at invokeFunc (webpack-internal:///./node_modules/lodash/lodash.js:11017:23)
```

</details>

Will try to investigate further.

**Comment by auchenberg** [comment]
@IllusionMH Quite interesting you are getting sub pixel values back. Pushed a fix to master. If you pull the extension and launch from within VS Code you should be able to get a full browser preview. Running `npm start` only gives you the frontend, without the Chrome headless.
